### ISSUE TITLE
Possibility to load Native Video behind the webview

### ISSUE THREAD

**Issue by mark-veenstra** [opentok/cordova-plugin-opentok#27]
It would be nice to be able to place the native camera's in front of or behind the webview based on the given `z-index`. Because if we could place the native video elements behind the webview we could also place HTML buttons on top of the video.

We have been successfull in placing the video behind the WebView with the Android and iOS , see branch:
https://github.com/Mediapioniers/cordova-plugin-opentok/tree/feat.cams_behind_webview_z-index

We got this technique from the [cordova-plugin-qrscanner](https://github.com/bitpay/cordova-plugin-qrscanner) and [cordova-plugin-iosrtc](https://github.com/Mediapioniers/cordova-plugin-opentok/commit/21a7c77b8dc48e4c11247f5da3ef05f8da8c7db5). 

So if you use our [branch](https://github.com/Mediapioniers/cordova-plugin-opentok/commits/feat.cams_behind_webview), the camera will be placed below the WebView based on the `z-index`. So to be able to see the cams and buttons, you need make everything transparent in your DOM, for example:
```css
# We can use class OT_root in our repository, but the main things is that the publisher container gets a black background color from OT, this needs to be removed in your CSS!
html, body, .OT_root {
  background: transparent !important;
}

# Each publisher and eachsubscriber video element should have display none
.OT_root video {
  display: none !important;
}
```
Also the inserted `<video>` tags for publishers and subsscribers in the DOM on Android need to get the `style="display: none;`.

When all is set you can have buttons on top of the video. See next screenshot:
![screenshot_20180209-165551](https://user-images.githubusercontent.com/8984015/36037013-b89ccaf0-0dbb-11e8-97da-d53d3fdf8895.png)
